name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # https://zellwk.com/blog/github-actions-deploy/
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
    
    - name: Update the server
      run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} './capstone_site/.ci/update.sh > last_run.log'
    
    - name: build the site
      run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} './capstone_site/.ci/deploy.sh >> last_run.log'